# i3status configuration
# 
# Copyright (c) 2018-2026, Augusto Damasceno.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#
# See https://github.com/augustodamasceno/dotfiles
#

general {
        colors = true
        interval = 1
}

order += "run_watch sshd"
order += "run_watch docker"
order += "disk /"
order += "ethernet enp1s0"
order += "ethernet tun0"
order += "wireless wlp0s20f3"
order += "battery 0"
order += "load"
order += "cpu_usage"
order += "memory"
order += "volume master"
order += "tztime local"


disk "/" {
	format = "⛁: %avail"
}

ethernet tun0 {
  format_up = "vpn on"
  format_down = "vpn off"
}

wireless wlp0s20f3 {
    format_up = "W: (%quality at %essid) %ip"
    format_down = "W: down"
}

battery 0 {
	format = "⚡: %status %percentage"
}

load {
	format = "load: %1min %5min %15min"
}

cpu_usage {
    format = "cpu: %usage"
}

memory {
	format = "mem: %available"
	threshold_degraded = "20%"
	threshold_critical = "10%"
	format_degraded = "Memory LOW: %free"
}

volume master {
    format = "♪: %volume"
	format_muted = "♩: %volume"
    device = "default"
    mixer = "Master"
    mixer_idx = "0"
}

tztime local {
    format = "%a, %d %b - %H:%M:%S"
}

run_watch sshd {
    pidfile = "/var/run/sshd.pid"
    format = "ssh: on"
    format_down = ""
}

run_watch docker {
    pidfile = "/var/run/docker.pid"
    format = "docker: on"
    format_down = ""
}
