services:
  mongo-playground:
    image: mongo:latest
    container_name: playground_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: playground
      MONGO_INITDB_ROOT_PASSWORD: playground
      MONGO_INITDB_DATABASE: playground
    ports:
      - "65002:27017"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - mongo_data:/data/db
    storage_opt:
      size: 2G

volumes:
  mongo_data:
    driver: local
